"""add name to faculty

Revision ID: 07c1ff1ff0e1
Revises: e066ce706c07
Create Date: 2026-02-08 17:12:09.255641

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07c1ff1ff0e1'
down_revision = 'e066ce706c07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_programme_course_offerings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('semester_no', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('semester_no BETWEEN 1 AND 6', name='chk_semester_range'),
    sa.ForeignKeyConstraint(['course_id'], ['tbl_courses.id'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['tbl_faculty.id'], ),
    sa.ForeignKeyConstraint(['programme_id'], ['tbl_programmes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('programme_id', 'course_id', name='uq_programme_course_once')
    )
    op.drop_table('tbl_programme_course')
    op.drop_table('tbl_course_faculty')
    with op.batch_alter_table('tbl_faculty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=128), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_faculty', schema=None) as batch_op:
        batch_op.drop_column('name')

    op.create_table('tbl_course_faculty',
    sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('faculty_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['tbl_courses.id'], name=op.f('tbl_course_faculty_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['tbl_faculty.id'], name=op.f('tbl_course_faculty_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'faculty_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tbl_programme_course',
    sa.Column('programme_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['tbl_courses.id'], name=op.f('tbl_programme_course_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['programme_id'], ['tbl_programmes.id'], name=op.f('tbl_programme_course_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('programme_id', 'course_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('tbl_programme_course_offerings')
    # ### end Alembic commands ###
