"""Add versioning to Templates

Revision ID: 35d88f2009f0
Revises: 682eb6ebb751
Create Date: 2026-03-04 10:11:37.230729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d88f2009f0'
down_revision = '682eb6ebb751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        
        # Drop the foreign key constraint first
        batch_op.drop_constraint('tbl_templates_ibfk_1', type_='foreignkey')
        
        # Now drop the unique index
        batch_op.drop_index('course_id')

        # Recreate the foreign key constraint without uniqueness
        batch_op.create_foreign_key('tbl_templates_ibfk_1', 'tbl_courses', ['course_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('course_id'), ['course_id'], unique=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
