"""empty message

Revision ID: 4a9710fa0168
Revises: 8febb06ead1a
Create Date: 2026-02-16 14:27:50.464146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a9710fa0168'
down_revision = '8febb06ead1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_course_outcomes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('learning_domains', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_course_outcomes', schema=None) as batch_op:
        batch_op.drop_column('learning_domains')

    # ### end Alembic commands ###
