"""Add level and batch to Programme

Revision ID: 682eb6ebb751
Revises: cea74f3d0897
Create Date: 2026-03-04 09:39:47.896017

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '682eb6ebb751'
down_revision = 'cea74f3d0897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_generated_papers', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tbl_courses', ['course_id'], ['id'])
        batch_op.create_foreign_key(None, 'tbl_templates', ['template_id'], ['id'])

    with op.batch_alter_table('tbl_programmes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('batch', sa.String(length=32), nullable=True))

    with op.batch_alter_table('tbl_questions', schema=None) as batch_op:
        batch_op.alter_column('difficulty',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_questions', schema=None) as batch_op:
        batch_op.alter_column('difficulty',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('tbl_programmes', schema=None) as batch_op:
        batch_op.drop_column('batch')
        batch_op.drop_column('level')

    with op.batch_alter_table('tbl_generated_papers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
