"""Add is_active to Programme

Revision ID: 7bcaa13a77a8
Revises: 35d88f2009f0
Create Date: 2026-03-04 11:29:41.684963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bcaa13a77a8'
down_revision = '35d88f2009f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_programmes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_programmes', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
