"""empty message

Revision ID: 8febb06ead1a
Revises: c82a33040b12
Create Date: 2026-02-15 18:39:57.566209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8febb06ead1a'
down_revision = 'c82a33040b12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hod_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tbl_faculty', ['hod_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_departments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('hod_id')

    # ### end Alembic commands ###
