"""empty message

Revision ID: 9a9633fff1ed
Revises: 4a9710fa0168
Create Date: 2026-02-18 00:47:41.826599

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a9633fff1ed'
down_revision = '4a9710fa0168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_type', sa.String(length=32), nullable=False))
        batch_op.drop_column('difficulty')
        batch_op.drop_column('bloom_level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bloom_level', mysql.VARCHAR(length=32), nullable=False))
        batch_op.add_column(sa.Column('difficulty', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('question_type')

    # ### end Alembic commands ###
