"""empty message

Revision ID: cea74f3d0897
Revises: 9a9633fff1ed
Create Date: 2026-02-18 09:48:37.114446

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cea74f3d0897'
down_revision = '9a9633fff1ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bloom_level', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('difficulty', sa.Integer(), nullable=True))
        batch_op.drop_column('question_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_type', mysql.VARCHAR(length=32), nullable=False))
        batch_op.drop_column('difficulty')
        batch_op.drop_column('bloom_level')

    # ### end Alembic commands ###
