"""Programme semester course offering model

Revision ID: e066ce706c07
Revises: 
Create Date: 2026-01-30 12:04:48.612608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e066ce706c07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tbl_superadmins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tbl_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('home_department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['home_department_id'], ['tbl_departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tbl_faculty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['tbl_departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tbl_programmes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['tbl_departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_course_faculty',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['tbl_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['tbl_faculty.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'faculty_id')
    )
    op.create_table('tbl_course_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['tbl_courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_generated_papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('total_marks', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('generated_by', sa.Integer(), nullable=False),
    sa.Column('co_weightages_snapshot', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['tbl_faculty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_programme_course',
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['tbl_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['programme_id'], ['tbl_programmes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('programme_id', 'course_id')
    )
    op.create_table('tbl_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('total_marks', sa.Integer(), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('bloom_distribution', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['tbl_courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id')
    )
    op.create_table('tbl_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('parent_topic_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('co_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['co_id'], ['tbl_course_outcomes.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['tbl_courses.id'], ),
    sa.ForeignKeyConstraint(['parent_topic_id'], ['tbl_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('mark_value', sa.Integer(), nullable=False),
    sa.Column('bloom_level', sa.String(length=32), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['tbl_courses.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['tbl_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_generated_paper_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('mark_value', sa.Integer(), nullable=False),
    sa.Column('section_label', sa.String(length=64), nullable=True),
    sa.Column('co_satisfied', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['tbl_generated_papers.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['tbl_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_generated_paper_questions')
    op.drop_table('tbl_questions')
    op.drop_table('tbl_topics')
    op.drop_table('tbl_templates')
    op.drop_table('tbl_programme_course')
    op.drop_table('tbl_generated_papers')
    op.drop_table('tbl_course_outcomes')
    op.drop_table('tbl_course_faculty')
    op.drop_table('tbl_programmes')
    op.drop_table('tbl_faculty')
    op.drop_table('tbl_courses')
    op.drop_table('tbl_superadmins')
    op.drop_table('tbl_departments')
    # ### end Alembic commands ###
